name: Create Cluster

on: [push, pull_request]


jobs:

  create-cluster:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2
      
      # helm is already installed
      - name: install k3d
        run: |
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          curl -L https://github.com/rancher/k3d/releases/download/v4.2.0/k3d-linux-amd64 --output k3d-linux-amd64
          mv k3d-linux-amd64 $HOME/.local/bin/k3d
          chmod +x $GITHUB_WORKSPACE/bin/k3d
      
      - name: helm
        run: helm --help
        
      - name: k3d
        run: k3d --help

      - name: prepare env
        working-directory: ./scripts
        run: chmod +x ./setup_env.sh && ./setup_env.sh
