name: Create Cluster

on: [push, pull_request]


jobs:

  create-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          config: ./scripts/kind.config.yaml
          wait: 400s

      - name: kind version
        run: kind --version

      - name: kubectl cluster-info
        run: kubectl cluster-info

      - name: install helm
        run: |
          mkdir -p $GITHUB_WORKSPACE/bin
          export PATH=$PATH:$GITHUB_WORKSPACE/bin
          curl https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz --output helm.temp.tar
          mkdir helm.temp.bin
          tar -zxvf helm.temp.tar -C helm.temp.bin
          mv helm.temp.bin/linux-amd64/helm $GITHUB_WORKSPACE/bin/helm
          rm -rf helm.temp.bin helm.temp.tar
          chmod +x $GITHUB_WORKSPACE/bin/helm

      - name: setup env
        working-directory: ./scripts
        run: chmod +x ./setup_env.sh && ./setup_env.sh
      
      - name: trust certs
        working-directory: ./scripts
        run: sudo cp ./cert.crt /usr/local/share/ca-certificates/kind-ingress.crt && sudo update-ca-certificates

      - name: check nginx http
        run: curl -s http://localhost:32080
          # '[[ "$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:32080)" == 404 ]] || echo fail && exit 1'

      - name: check nginx https
        run: curl -s https://localhost:32443
          # '[[ "$(curl -o /dev/null -s -w "%{http_code}\n" https://localhost:32443)" == 404 ]] || echo fail && exit 1'
